In [1]:
%use dataframe
%use kandy
import profilelib.*

In [2]:
val profileData = load_data("jfrs/serialization/cstack_dwarf/") { it
    .filterNot { it.any { it.method.name.contains("::Sweep<") } }
    .filterNot { it.any { it.method.name.contains("JsonToStringWriter") } }
}

'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=43,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=10.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=44,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=50,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=20,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=48,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=67,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=8.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=33,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=26.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=25,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=63,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=29,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=45,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=81.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=76.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=73.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=14,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=83.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=70.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=6.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=80,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=97,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=27.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=40.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=34.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=40,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=83,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=23.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=4.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=32,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=92.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=79,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=72,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=13,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=91,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=74,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=44.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=61,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=57.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=99.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=77,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=47,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=65.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=55,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=64.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=50.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=43.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=28.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=98.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=58,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=20.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=39,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=94.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=47.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=23,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=92,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=51.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=88,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=93,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=24,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=51,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=60.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=42.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=12.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=53.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=22,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=91.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=69.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=97.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=96.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=62,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=74.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=7.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=41.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=58.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=76,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=57,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=75.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=16,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=17.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=46.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=84,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=9,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=9.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=3,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=68,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=1,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=1.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=73,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=96,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=26,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=10,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=18,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=82.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=37.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=46,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=19.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=59.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=25.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=36,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=72.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=2,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=71.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=66,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=17,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=15.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=59,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=95.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=53,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=60,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=34,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=12,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=87,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=49.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=85,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=21,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=61.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=77.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=31,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=28,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=27,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=38.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=jvm,cycles=100000,sampleInterval=100,iteration=54,warmup=3.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=2.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=5.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=21.jfr'
'/home/martinzimen/IdeaProjects/stdlib-profiling/data/jfrs/serialization/cstack_dwarf/platform=native,cycles=100000,sampleInterval=100,iteration=63.jfr'

In [3]:
fun getResult(name: String, jvmName: String, nativeName: String): Pair<String, Double> =
    profileData.funRatio(jvmName, nativeName)
    .map { it!! }
    .also { println(name + ": " + formattedMeanCV(it)) }
    .let { name to mean(it) }
val profileResults = mapOf(
    getResult("Map", "java.util.HashMap.get", "kotlin.collections.Map.get"),
    getResult("StringBuilder", "java.lang.StringBuilder.append", "kotlin.text.StringBuilder.append"),
    getResult("StringSubstring", "java.lang.String.substring", "weirdo:Kotlin_String_subSequence"),
)

Map: 0.129 (0.032)
StringBuilder: 0.154 (0.036)
StringSubstring: 0.174 (0.050)

In [4]:
@DataSchema
data class BenchmarkRow(
    val benchmark: String,
    val jvm: Double,
    val jvmError: Double,
    val native: Double,
    val nativeError: Double
)

fun loadAsDF(path: String): DataFrame<BenchmarkRow> {
    val jvm = loadScores(loadJson(dataPath(path.replace("*", "jvm"))))
    val native = loadScores(loadJson(dataPath(path.replace("*", "linuxX64"))))
    if (jvm.keys != native.keys) throw Exception()
    val benchmarks = jvm.keys.toList()

    fun Map<String, Double>.toNamedColumn(name: String): DataColumn<Double> = benchmarks
        .map { this[it]!! }
        .toColumn(name)

    return dataFrameOf(
        benchmarks.toColumn("benchmark"),
        jvm.mapValues { it.value.first }.toNamedColumn("jvm"),
        jvm.mapValues { it.value.second }.toNamedColumn("jvmError"),
        native.mapValues { it.value.first }.toNamedColumn("native"),
        native.mapValues { it.value.second }.toNamedColumn("nativeError"),
    ) as DataFrame<BenchmarkRow>
}

In [10]:
fun findControlName(bmName: String): String = when (bmName.substringBefore(".")) {
    "MapBenchmark" -> bmName
                        .replace(".konst{", ".konst_control{")
                        .replace(".random{", ".random_control{")
    "StringSubstringBenchmark" -> bmName.substringBefore("_") + "_control"
    "StringBuilderBenchmark" -> "StringBuilderBenchmark.control"
    else -> throw Exception()
}

val benchmarkDF = loadAsDF("benchmarks/report-selection-*.json")
    .filter { !benchmark.contains("ConstMapBenchmark") }
    .filter { !benchmark.contains("StringSubstringBenchmark.big") }
    .filter { !benchmark.endsWith("_none") }
    .filter { !benchmark.endsWith("_all") }
    .add("jvmControl") { df().single{ benchmark == findControlName(this@add.benchmark) }.jvm }
    .add("jvmControlError") { df().single{ benchmark == findControlName(this@add.benchmark) }.jvmError }
    .add("nativeControl") { df().single{ benchmark == findControlName(this@add.benchmark) }.native }
    .add("nativeControlError") { df().single{ benchmark == findControlName(this@add.benchmark) }.nativeError }
    .filter { !benchmark.contains("control") }

In [15]:
val percGCDF = dataFrameOf("benchmark", "jvm", "native")(
    "StringSubstringBenchmark.small_some", 0.012, 0.159,
    "StringSubstringBenchmark.medium_some", 0.012, 0.15
)
percGCDF

benchmark,jvm,native
StringSubstringBenchmark.small_some,0.012000,0.159000
StringSubstringBenchmark.medium_some,0.012000,0.150000

In [25]:
val benchmarkResults = benchmarkDF
    .add("ratio") { (jvm - jvmControl) / (native - nativeControl) }
    .add("ratioError") { propagateErrorThroughRatio(
        jvm - jvmControl,
        propagateErrorThroughSum(jvmError, jvmControlError),
        native - nativeControl,
        propagateErrorThroughSum(nativeError, nativeControlError),
    )}
    .add("ratiowGC") {
        percGCDF.singleOrNull{ this@add.benchmark == this@singleOrNull.benchmark }?.let { percGC ->
            (
                (1 - percGC.jvm) * (jvm - jvmControl)
            ) / (
                (1 - percGC.native) * (native - nativeControl)
            )
        } ?: this["ratio"] as Double
    }

In [26]:
benchmarkResults.select { benchmark and ratio and ratioError and ratiowGC }

benchmark,ratio,ratioError,ratiowGC
"MapBenchmark.konst{miss=""true"",size=""...",0.044342,0.000002,0.044342
"MapBenchmark.konst{miss=""true"",size=""...",0.051058,0.000002,0.051058
"MapBenchmark.konst{miss=""true"",size=""...",0.053358,0.000001,0.053358
"MapBenchmark.konst{miss=""true"",size=""...",0.052532,0.000000,0.052532
"MapBenchmark.konst{miss=""false"",size=...",0.048173,0.000002,0.048173
"MapBenchmark.konst{miss=""false"",size=...",0.047178,0.000003,0.047178
"MapBenchmark.konst{miss=""false"",size=...",0.054072,0.000001,0.054072
"MapBenchmark.konst{miss=""false"",size=...",0.054862,0.000001,0.054862
"MapBenchmark.random{miss=""true"",size=...",0.075438,0.000004,0.075438
"MapBenchmark.random{miss=""true"",size=...",0.080866,0.000003,0.080866
"MapBenchmark.random{miss=""true"",size=...",0.093769,0.000005,0.093769
"MapBenchmark.random{miss=""true"",size=...",0.255867,0.000001,0.255867
"MapBenchmark.random{miss=""false"",size...",0.063573,0.000000,0.063573
"MapBenchmark.random{miss=""false"",size...",0.078127,0.000001,0.078127
"MapBenchmark.random{miss=""false"",size...",0.068214,0.000001,0.068214
"MapBenchmark.random{miss=""false"",size...",0.138155,0.000005,0.138155
StringBuilderBenchmark.appendBig,0.116546,0.000408,0.116546
StringBuilderBenchmark.appendMedium,0.159089,0.000658,0.159089
StringBuilderBenchmark.appendSmall,0.102860,0.002575,0.102860
StringSubstringBenchmark.medium_some,0.172263,0.000005,0.200231

In [28]:
plot {
    points {
        x(benchmarkResults.benchmark.toList().map { it.substringBefore("Benchmark") })
        y(benchmarkResults.ratiowGC.toList())
    }
    points {
        x(profileResults.keys)
        y(profileResults.values)
        symbol = Symbol.CROSS
        size = 10.0
    }
}