In [13]:
import profilelib.*
%use dataframe

In [14]:
fun loadAsDF(path: String): DataFrame<*> {
    val jvm = loadScores(loadJson(path.replace("*", "jvm")))
    val native = loadScores(loadJson(path.replace("*", "linuxX64")))
    if (jvm.keys != native.keys) throw Exception()
    val benchmarks = jvm.keys.toList()

    fun Map<String, Double>.toNamedColumn(name: String): DataColumn<Double> = benchmarks
        .map { this[it]!! }
        .toColumn(name)

    return dataFrameOf(
        benchmarks.toColumn("benchmark"),
        jvm.toNamedColumn("jvm"),
        native.toNamedColumn("native"),
    )
}

In [15]:
loadAsDF("../../benchmarks/vanilla/report-map-*.json")
    .add("ratio") { this["native"] as Double / this["jvm"] as Double }

benchmark,jvm,native,ratio
"controlB{size=""10""}",759119857.326849,45320236.612710,0.059701
"controlB{size=""50""}",762446547.156493,44668290.257533,0.058585
"controlB{size=""100""}",763925819.198096,45450557.872337,0.059496
"controlB{size=""500""}",767693666.829037,45286895.911187,0.058991
"controlB{size=""1000""}",757783143.131827,44695049.715614,0.058981
"controlB{size=""5000""}",767072141.019164,44836739.441361,0.058452
"controlB{size=""10000""}",748218820.942364,46863722.060992,0.062634
"controlB{size=""50000""}",761032975.655372,46695816.083055,0.061358
"controlB{size=""100000""}",749865409.047599,46687021.726093,0.062261
"controlF{size=""10""}",746372402.644470,45220468.578308,0.060587
"controlF{size=""50""}",760969524.502987,45215823.667701,0.059419
"controlF{size=""100""}",756436675.706725,45771252.131533,0.060509
"controlF{size=""500""}",759090393.451881,45152667.178051,0.059483
"controlF{size=""1000""}",753351884.964016,45289561.174857,0.060117
"controlF{size=""5000""}",757180715.546386,45855316.491901,0.060561
"controlF{size=""10000""}",761764001.322986,45490798.341939,0.059718
"controlF{size=""50000""}",756191833.287449,46932557.855624,0.062064
"controlF{size=""100000""}",769621090.662845,45397941.261383,0.058987
"getB2{size=""10""}",502756629.986074,19413969.188104,0.038615
"getB2{size=""50""}",496003174.485132,19525703.131993,0.039366

In [16]:
loadAsDF("../../benchmarks/vanilla/report-stringbuilder-*.json")
    .add("ratio") { this["native"] as Double / this["jvm"] as Double }

benchmark,jvm,native,ratio
appendBig,2011.418537,251.584028,0.125078
appendMedium,1190.032920,197.422228,0.165896
appendSmall,191.171800,19.300317,0.100958